### ISSUE TITLE
[BUG] Duplicate XML errors XML RimWorld.ThoughtDef defines the same field twice: nullifyingTraits when More Practical Traits is loaded

### ISSUE THREAD

**Issue by Taranchuk** [Danimineiro/BucketOfTraits#1]
**Describe the bug**
Apparently, your xml patches are missing checks if nullifyingTraits already presents.  More Practical Traits does that internally, you could take a look at their xml patches
**To Reproduce**
1. Install More Practical Traits mod from this https://steamcommunity.com/sharedfiles/filedetails/?id=1568700181
2. Startup the game

**Expected behavior**
No xml errors

**Logs**
https://git.io/Jrq8b
**Screenshots**
If applicable, please add screenshots to help explain the bug.
https://imgur.com/a/LjrSMde
**My mod list**
(append your mod list here)

**Comment by Danimineiro** [comment]
On it

**Comment by Danimineiro** [comment]
Fixed in most recent update
