### ISSUE TITLE
[BUG] Exception when a slave ship appears

### ISSUE THREAD

**Issue by joseasoler** [Danimineiro/BucketOfTraits#10]
An `Exception ticking hediff (BOT_Fleeing` error appeared in the log when a slave ship appeared. I checked the stock of the ship afterwards, and the pawn mentioned in the error log has the Entomophobia trait. My assumption is that this trait creates a hediff, and that in this case the hediff is appearing before the pawn is spawned.

**HugsLib log:** https://gist.github.com/HugsLibRecordKeeper/5edf92f84dbece80f4ed96b90121b596

**Comment by Danimineiro** [comment]
Sorry, what's a slave ship? 
I want to see if I can reproduce this, so I can test if a fix would work

**Comment by joseasoler** [comment]
Slave ships are one of the orbital traders available in vanilla RimWorld. For an easier repro you could go to `Orbital_PirateMerchant` and increase the `countRange` of the `StockGenerator_Slaves` entry to a huge value, as I suspect the issue will only happen when one of the slaves has the Entomophobia trait.

**Comment by Danimineiro** [comment]
alright cool, will check out

**Comment by Danimineiro** [comment]
Could reproduce setting the commonality of the Trait to an absurd value
Suspected being able to fix it by checking if the pawn is spawned
