### ISSUE TITLE
[BUG] Red Exeption Unexpected Token

### ISSUE THREAD

**Issue by Narlindir** [Danimineiro/BucketOfTraits#5]
delet

**Comment by Narlindir** [comment]
I hope I dont waste your time with this
my save is behaving really funky (99% certanty not your mod)

### Describe the bug
Found a red error
![grafik](https://user-images.githubusercontent.com/88289802/149643249-c933d0aa-486f-4045-8179-15fc64f77380.png)
but my entire game is misbehaving badly
so this is probably not in your sphere of influence
but I think aside of that
you may or may not want to be aware of the bug/ exception

I cannot say with any confidence that any of my problems stem from this 
Just saw it while trying to sift through my logs cuz my game is falling apart

### To Reproduce
no reproduction attemted as of yet

### Expected behavior
not able to determine/ isolate faulty behavior

### Logs
Exception loading file at https://github.com/Danimineiro/BundleOfTraits/tree/master/About/Manifest.xml. Loading defaults instead. Exception was: System.Xml.XmlException: '>' is an unexpected token. The expected token is '='. Line 15, position 76.
  at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x00027] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlTextReaderImpl.Throw (System.String res, System.String[] args) [0x00029] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken (System.String expectedToken1, System.String expectedToken2) [0x00036] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken (System.String expectedToken1) [0x00000] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlTextReaderImpl.ParseAttributes () [0x002ae] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlTextReaderImpl.ParseElement () [0x001df] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlTextReaderImpl.ParseElementContent () [0x0016f] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlTextReaderImpl.Read () [0x00085] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlLoader.LoadNode (System.Boolean skipOverWhitespace) [0x0025b] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlLoader.LoadDocSequence (System.Xml.XmlDocument parentDoc) [0x0001b] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlLoader.Load (System.Xml.XmlDocument doc, System.Xml.XmlReader reader, System.Boolean preserveWhitespace) [0x000b4] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlDocument.Load (System.Xml.XmlReader reader) [0x0002e] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlDocument.LoadXml (System.String xml) [0x00018] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at Verse.DirectXmlLoader.ItemFromXmlString[T] (System.String xmlContent, System.String filePath, System.Boolean resolveCrossRefs) [0x0001a] in <cdbd0ed5089a418da09b9a259f9dbd8f>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch3 (string)
Verse.DirectXmlLoader:ItemFromXmlString<ModManager.Manifest> (string,string,bool)
ModManager.VersionCheck/<FetchManifest>d__19:MoveNext ()
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:InvokeMoveNext (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
System.Threading.Tasks.AwaitTaskContinuation:InvokeAction (object)
System.Threading.Tasks.AwaitTaskContinuation:RunCallback (System.Threading.ContextCallback,object,System.Threading.Tasks.Task&)
System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run (System.Threading.Tasks.Task,bool)
System.Threading.Tasks.Task:FinishContinuations ()
System.Threading.Tasks.Task:FinishStageThree ()
System.Threading.Tasks.Task`1<string>:TrySetResult (string)
System.Threading.Tasks.TaskCompletionSource`1<string>:TrySetResult (string)
System.Net.WebClient:HandleCompletion<System.Net.DownloadStringCompletedEventArgs, System.Net.DownloadStringCompletedEventHandler, string> (System.Threading.Tasks.TaskCompletionSource`1<string>,System.Net.DownloadStringCompletedEventArgs,System.Func`2<System.Net.DownloadStringCompletedEventArgs, string>,System.Net.DownloadStringCompletedEventHandler,System.Action`2<System.Net.WebClient, System.Net.DownloadStringCompletedEventHandler>)
System.Net.WebClient/<>c__DisplayClass219_0:<DownloadStringTaskAsync>b__0 (object,System.Net.DownloadStringCompletedEventArgs)
System.Net.WebClient:OnDownloadStringCompleted (System.Net.DownloadStringCompletedEventArgs)
System.Net.WebClient:DownloadStringOperationCompleted (object)
UnityEngine.UnitySynchronizationContext/WorkRequest:Invoke ()
UnityEngine.UnitySynchronizationContext:Exec ()
UnityEngine.UnitySynchronizationContext:ExecuteTasks ()

[Player.log](https://github.com/Danimineiro/BundleOfTraits/files/7876175/Player.log)
[Player-prev.log](https://github.com/Danimineiro/BundleOfTraits/files/7876177/Player-prev.log)
[New Vault1.1642295032540 Bug.rws.zip](https://github.com/Danimineiro/BundleOfTraits/files/7876180/New.Vault1.1642295032540.Bug.rws.zip)
[Saves.zip](https://github.com/Danimineiro/BundleOfTraits/files/7876191/Saves.zip)

### Screenshots
![grafik](https://user-images.githubusercontent.com/88289802/149643249-c933d0aa-486f-4045-8179-15fc64f77380.png)

**Comment by Narlindir** [comment]
### Modlist
https://rentry.co/y87br

also https://steamcommunity.com/sharedfiles/filedetails/?id=2601386195
I think its missing from that list

**Comment by Danimineiro** [comment]
Der Fehler kommt von einem Fehler in der einen Manifest Datei da - aber den kannst du ganz ehrlich ignorieren

Ich schau sobald ich kann ob ich sehe was das Problem ist, aber kann nichts wirklich garantieren

Es wäre aber schon eher hilfreich wenn du mir den HugsLib log senden würdest, drück dafür in dem Menü welches du in deinem screenshot offen hast auf den grünen "Log Teilen" Knopf unten links nach dem du das Problem beobachtet hast

Der Log hat ein paar mehr Informationen über Patches u.Ä. die beim suchen sehr hilfreich sein können

**Comment by Narlindir** [comment]
Oh hey
Unerwartet deutsch ^^


Ich muss mich entschuldigen
Ich hab versucht ein Log mit dem F12 menü zu erstellen, aber hat nicht geklappt
den großen grünen Knopf hab ich komplett übersehen
hab heute versucht das zu replizieren indem ich die mods mit dem save synchronisiere über RimPy
aber es ist einfach alles am brennen

Ich hab den verdacht dass der aktuelle status von "Savegame Compressor" ausgelöst wurde
Ich kann nicht mal den save mehr importieren um nen log zu erstellen

Ich versuch mal ne neue welt zu erstellen und davon nen log zu Posten (aber bezweifle dass dir das sehr hinfreich ist)

Ich schließe mal den thread 
wenn ich irgendwas in die richtung nochmal finden kann schreib ich nochmal
aber mein game ist einfach nur noch eine katastrophe lul

**Comment by Narlindir** [comment]
This is Fine

**Comment by Narlindir** [comment]
https://gist.github.com/HugsLibRecordKeeper/fcd2076f713d6e8d20d62b545013ceef
its a log
but a later one sorry
this is probaly not useful in the slightest
no sign of this error too
I will update you If I find something actually worthwhile
